spring.application.name=RoleBasedAuthentication

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/RoleBasedAuth
spring.datasource.username=krityankashyap
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${jwt_secret}
jwt.expiration=${jwt_expiration}
